spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.131.131:3306/micro_mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: micro-mall-member
mybatis-plus:
  # mapper文件扫描
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 数据库主键自增
server:
  port: 8000